# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-12 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256, verbose_name='公司名称')),
                ('zhiwei', models.CharField(max_length=256, verbose_name='职位')),
                ('position', models.CharField(max_length=256, verbose_name='地理位置')),
                ('money', models.CharField(max_length=256, verbose_name='薪资范围')),
                ('exp', models.CharField(max_length=256, verbose_name='经验')),
                ('xueli', models.CharField(max_length=10, verbose_name='学历')),
                ('industry', models.CharField(max_length=256, verbose_name='行业')),
                ('rongzi', models.CharField(max_length=10, verbose_name='融资阶段')),
                ('skill_type', models.IntegerField(choices=[(0, '后端开发'), (1, '移动开发'), (2, '前端开发'), (3, '人工智能'), (4, '测试'), (5, '运维'), (6, '数据库')], verbose_name='技术类型')),
                ('sort', models.IntegerField(choices=[(0, 'java'), (1, 'c++'), (2, 'php'), (3, 'python'), (4, 'HTML5'), (5, 'android'), (6, 'ios'), (7, 'wp'), (8, 'web前端'), (9, 'Flash'), (10, 'html5'), (11, 'javascript'), (12, '深度学习'), (13, '机器学习'), (14, '图像处理'), (15, '图像识别'), (16, '测试工程师'), (17, '自动化测试'), (18, '功能测试'), (19, '性能测试'), (20, '运维工程师'), (21, '运维开发工程师'), (22, '网络工程师'), (23, '系统工程师'), (24, 'mysql'), (25, 'sqlserver'), (26, 'oracle'), (27, 'DB2')], verbose_name='类型')),
            ],
        ),
    ]
